### ISSUE TITLE
Documentation URL is invalid in README

### ISSUE THREAD

**Issue by nishantnath** [hyperwallet/python-sdk#31]
Is there an updated version , SDK specific or we need to deconstruct from Generic API Docs?

**Comment by alimony** [comment]
@nishantnath Which URL is this? Can't find any invalid ones in the current README.

**Comment by nishantnath** [comment]
The REST API Reference: https://portal.hyperwallet.com/docs
wasn't resolving to the correct destination (https://docs.hyperwallet.com/content/hyperwallet-payout-documentation) back in Feb. Seems ok now. Closing this.
